### ISSUE TITLE
[question] api source reliability

### ISSUE THREAD

**Issue by peterlupu** [ciprian-chichirita/romanian-bank-holidays#5]
hi, i might be offtopic but how reliable is https://us-central1-romanian-bank-holidays.cloudfunctions.net/romanian_bank_holidays/ ? 

can we expect it to work 1-2-3 years from now?

a quick google for "zile libere api" got me here and it seems this information is rather scarce

thank you!

**Comment by ciprian-chichirita** [comment]
I don't know how reliable will be, you can use the source code for it.
It was made for a personal project of mine, this is more of an eg. for me to remember in the future what I did :)

**Comment by peterlupu** [comment]
alright, thank you :)
